spring.datasource:
  driverClassName: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/spring_started
  username: root
  password: developer
  dialect: org.hibernate.dialect.MySQL5Dialect

spring.jpa:
  show-sql: true
  hibernate:
    dialect: org.hibernate.dialect.MySQL5Dialect
    ddl-auto: none
    hikari:
      maximumPoolSize: 50
